"""migration3

Revision ID: 0f48c217174c
Revises: 11dd6c2b57eb
Create Date: 2025-01-03 16:16:45.664860

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f48c217174c'
down_revision: Union[str, None] = '11dd6c2b57eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('event_event_category_event_id_fkey', 'event_event_category', type_='foreignkey')
    op.drop_constraint('event_event_category_event_category_id_fkey', 'event_event_category', type_='foreignkey')
    op.create_foreign_key(None, 'event_event_category', 'event_categories', ['event_category_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'event_event_category', 'events', ['event_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'event_event_category', type_='foreignkey')
    op.drop_constraint(None, 'event_event_category', type_='foreignkey')
    op.create_foreign_key('event_event_category_event_category_id_fkey', 'event_event_category', 'event_categories', ['event_category_id'], ['id'])
    op.create_foreign_key('event_event_category_event_id_fkey', 'event_event_category', 'events', ['event_id'], ['id'])
    # ### end Alembic commands ###
