"""migration2

Revision ID: 11dd6c2b57eb
Revises: f8dcec762ee2
Create Date: 2025-01-03 15:17:46.365346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11dd6c2b57eb'
down_revision: Union[str, None] = 'f8dcec762ee2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('_sort_order_uc', 'event_categories', ['sort_order'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_sort_order_uc', 'event_categories', type_='unique')
    # ### end Alembic commands ###
