"""2

Revision ID: 53b38fd0b96e
Revises: 4fd6cb580812
Create Date: 2025-01-02 18:45:17.528329

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '53b38fd0b96e'
down_revision: Union[str, None] = '4fd6cb580812'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendees',
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', name='attendance_status', create_type=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'user_id', name='uix_event_user')
    )
    op.drop_table('event_attendees')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_attendees',
    sa.Column('status', postgresql.ENUM('pending', 'approved', 'rejected', name='attendancestatus'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('event_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name='event_attendees_event_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='event_attendees_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='event_attendees_pkey')
    )
    op.drop_table('attendees')
    # ### end Alembic commands ###
