"""Add foreign keys to Event

Revision ID: 7beeb9be0a10
Revises: 7c5dd654bae4
Create Date: 2024-12-27 15:45:27.124830

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7beeb9be0a10'
down_revision: Union[str, None] = '7c5dd654bae4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('user_id', sa.Integer(), nullable=False))
    op.add_column('events', sa.Column('country_id', sa.Integer(), nullable=False))
    op.add_column('events', sa.Column('region_id', sa.Integer(), nullable=False))
    op.drop_constraint('events_organizer_id_fkey', 'events', type_='foreignkey')
    op.create_foreign_key(None, 'events', 'regions', ['region_id'], ['id'])
    op.create_foreign_key(None, 'events', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'events', 'countries', ['country_id'], ['id'])
    op.drop_column('events', 'organizer_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('organizer_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.create_foreign_key('events_organizer_id_fkey', 'events', 'users', ['organizer_id'], ['id'])
    op.drop_column('events', 'region_id')
    op.drop_column('events', 'country_id')
    op.drop_column('events', 'user_id')
    # ### end Alembic commands ###
