"""3

Revision ID: 7c5dd654bae4
Revises: bc9f9013f97a
Create Date: 2024-12-26 13:53:56.687156

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c5dd654bae4'
down_revision: Union[str, None] = 'bc9f9013f97a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('regions', 'code')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('regions', sa.Column('code', sa.VARCHAR(length=10), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
