"""2

Revision ID: bc9f9013f97a
Revises: 133f8e6c7a8e
Create Date: 2024-12-26 13:49:20.869241

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc9f9013f97a'
down_revision: Union[str, None] = '133f8e6c7a8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('regions',
    sa.Column('name_en', sa.String(length=255), nullable=True),
    sa.Column('name_ru', sa.String(length=255), nullable=True),
    sa.Column('name_uz', sa.String(length=255), nullable=True),
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('region_id', sa.Integer(), nullable=True))
    op.create_index('idx_users_region_id', 'users', ['region_id'], unique=False)
    op.create_foreign_key(None, 'users', 'regions', ['region_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index('idx_users_region_id', table_name='users')
    op.drop_column('users', 'region_id')
    op.drop_table('regions')
    # ### end Alembic commands ###
