"""migration name

Revision ID: c9a0d91df015
Revises: 317f3a4e14c5
Create Date: 2024-12-30 12:22:43.567077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9a0d91df015'
down_revision: Union[str, None] = '317f3a4e14c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('events', 'country_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('events', 'region_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('events', 'region_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('events', 'country_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
