"""migration name

Revision ID: d68177a64013
Revises: 7beeb9be0a10
Create Date: 2024-12-28 21:15:16.524259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd68177a64013'
down_revision: Union[str, None] = '7beeb9be0a10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('events', 'description',
               existing_type=sa.VARCHAR(length=2048),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('events', 'description',
               existing_type=sa.VARCHAR(length=2048),
               nullable=True)
    # ### end Alembic commands ###
