"""migration name

Revision ID: e805b6f8c5a5
Revises: 53b38fd0b96e
Create Date: 2025-01-02 21:42:57.204986

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e805b6f8c5a5'
down_revision: Union[str, None] = '53b38fd0b96e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.alter_column('attendees', 'status',
    #            existing_type=postgresql.ENUM('pending', 'approved', 'rejected', name='attendance_status'),
    #            type_=sa.Enum('pending', 'approved', 'rejected', name='attendancestatus'),
    #            existing_nullable=False)
    op.add_column('events', sa.Column('is_occurred', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('events', sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'is_deleted')
    op.drop_column('events', 'is_occurred')
    # op.alter_column('attendees', 'status',
    #            existing_type=sa.Enum('pending', 'approved', 'rejected', name='attendancestatus'),
    #            type_=postgresql.ENUM('pending', 'approved', 'rejected', name='attendance_status'),
    #            existing_nullable=False)
    # ### end Alembic commands ###
