"""21dec2

Revision ID: 1407646cfdc5
Revises: f45eaf2d6649
Create Date: 2024-12-21 11:06:20.141947

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1407646cfdc5'
down_revision: Union[str, None] = 'f45eaf2d6649'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'country_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('users', 'region_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'region_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('users', 'country_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
