"""21dec4

Revision ID: 2ac572a48c45
Revises: ab76f3889103
Create Date: 2024-12-21 11:20:01.638114

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ac572a48c45'
down_revision: Union[str, None] = 'ab76f3889103'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_users_region_id', table_name='users')
    op.drop_constraint('users_region_id_fkey', 'users', type_='foreignkey')
    op.drop_column('users', 'region_id')
    op.drop_table('region_translations')
    op.drop_table('regions')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('region_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('users_region_id_fkey', 'users', 'regions', ['region_id'], ['id'])
    op.create_index('idx_users_region_id', 'users', ['region_id'], unique=False)
    op.create_table('regions',
    sa.Column('country_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('code', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('regions_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], name='regions_country_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='regions_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('region_translations',
    sa.Column('region_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('language_code', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['region_id'], ['regions.id'], name='region_translations_region_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='region_translations_pkey'),
    sa.UniqueConstraint('region_id', 'language_code', name='uix_region_language')
    )
    # ### end Alembic commands ###
